{
    "docs": "https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/pep8.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pep8` [[explain](https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/pep8.html)] failed with 1 error:", 
            "output": "plugins/modules/axway_cft_facts.py:108:7: E121: continuation line under-indented for hanging indent"
        }
    ], 
    "verified": false
}
