{
    "docs": "https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/pylint.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pylint` [[explain](https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/pylint.html)] failed with 1 error:", 
            "output": "plugins/module_utils/common.py:16:0: bare-except: No exception type(s) specified"
        }
    ], 
    "verified": false
}
